### ISSUE TITLE
Driver info: driver.version: unknown on Selenium Grid

### ISSUE THREAD

**Issue by SalimAnsari1808** [blibli-badak/selenium-har-util#25]
Things are working fine when I am running on my local machine however on remote using Selenium Grid I am getting error:
Java: 11
Selenium: 4.9.1
Chrome:114

2023-09-06 15:41:40,931 [TestNG-tests-1] INFO  - Starting Test Case HeartBeat1 on CHROME Browser
Sep 06, 2023 3:41:52 PM org.openqa.selenium.devtools.Connection$Listener lambda$onText$0
WARNING: Unable to process: {"method":"Fetch.requestPaused","params":{"requestId":"interception-job-11.0","request":{"url":"https://www.******.com/main.b6b5cec8ea30ad52.js","method":"GET","headers":{"Accept":"*/*","Cookie":"userCountryLocation=US; userGeolocation=-75.3441, 40.3745; _pxhd=f5d2accc9007d3813fe9cfccf84cb3927bcbe82bd0e92bc60a9126530445fd2b:670a4f95-4ced-11ee-bf6b-f19d2e06fe22","Origin":"https://www.******.com","Referer":"https://www.******.com/?&test_type=Guest_Happy_Path_DOM_OW_2Adults_2Children_No_Ancillaries","User-Agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36","sec-ch-ua":"\"Not.A/Brand\";v=\"8\", \"Chromium\";v=\"114\", \"Google Chrome\";v=\"114\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"Linux\""},"initialPriority":"High","referrerPolicy":"unsafe-url"},"frameId":"0825FD7CF11E00479267175BDC8FE68F","resourceType":"Script","responseStatusCode":200,"responseStatusText":"","responseHeaders":[{"name":"accept-ranges","value":"bytes"},{"name":"content-type","value":"application/x-javascript"},{"name":"etag","value":"\"beefa8c88db402518b53ca0f586fd620:1692783088.285696\""},{"name":"last-modified","value":"Wed, 23 Aug 2023 09:31:28 GMT"},{"name":"server","value":"AkamaiNetStorage"},{"name":"vary","value":"Accept-Encoding"},{"name":"content-encoding","value":"gzip"},{"name":"cache-control","value":"max-age=1787"},{"name":"expires","value":"Wed, 06 Sep 2023 20:11:29 GMT"},{"name":"date","value":"Wed, 06 Sep 2023 19:41:42 GMT"},{"name":"access-control-max-age","value":"86400"},{"name":"access-control-allow-credentials","value":"false"},{"name":"access-control-allow-headers","value":"*"},{"name":"access-control-allow-methods","value":"GET,POST"},{"name":"access-control-allow-origin","value":"*"},{"name":"x-frame-options","value":"DENY"}]},"sessionId":"BF5F1678D1D07C95712D467AF6D13384"}
org.openqa.selenium.WebDriverException: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.17'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.idealized.Network.lambda$prepareToInterceptTraffic$4(Network.java:230)
	at org.openqa.selenium.devtools.Connection.lambda$handle$6(Connection.java:304)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:442)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1621)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:273)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:59)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:215)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.17'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:175)
	at org.openqa.selenium.devtools.DevTools.send(DevTools.java:81)
	at org.openqa.selenium.devtools.v113.v113Network.createSeMessages(v113Network.java:137)
	at org.openqa.selenium.devtools.v113.v113Network.createSeMessages(v113Network.java:54)
	at org.openqa.selenium.devtools.idealized.Network.lambda$prepareToInterceptTraffic$4(Network.java:185)
	... 17 more
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:164)
	... 21 more

Exception in thread "CDP Connection" org.openqa.selenium.devtools.DevToolsException: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.17'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:218)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.openqa.selenium.WebDriverException: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.17'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.idealized.Network.lambda$prepareToInterceptTraffic$4(Network.java:230)
	at org.openqa.selenium.devtools.Connection.lambda$handle$6(Connection.java:304)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:442)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1621)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:273)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:59)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:215)
	... 3 more
Caused by: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.17'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:175)
	at org.openqa.selenium.devtools.DevTools.send(DevTools.java:81)
	at org.openqa.selenium.devtools.v113.v113Network.createSeMessages(v113Network.java:137)
	at org.openqa.selenium.devtools.v113.v113Network.createSeMessages(v113Network.java:54)
	at org.openqa.selenium.devtools.idealized.Network.lambda$prepareToInterceptTraffic$4(Network.java:185)
	... 17 more
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:164)
	... 21 more

**Comment by SalimAnsari1808** [comment]
I am using Selenium Util version. 1.0.10

**Comment by MHabiib** [comment]
hi @SalimAnsari1808 , for remote execution you need to convert your driver to RemoteWebDriver
for example:
`public static RemoteWebDriver getProxyiedDriverRemote(WebDriverFacade driver) {
        return (RemoteWebDriver) driver.getProxiedDriver();
    }`

**Comment by SalimAnsari1808** [comment]
Hello @MHabiib,
I am using remote driver to run the test case, let me check and get back to you again also Please let me know what value I have to use in 'baseRemoteUrl'

**Comment by SalimAnsari1808** [comment]
[
![image](https://github.com/blibli-badak/selenium-har-util/assets/46842395/7a09befa-7d5a-44eb-bece-e6c5041336f7)
](url)

**Comment by SalimAnsari1808** [comment]
Hello @MHabiib,
Kindly, look into this issue and provide your valuable feedback

**Comment by cr-liorholtzman** [comment]
@MHabiib can you elaborate more on the steps we need to run to make it work remotely with Selenium Grid as I'm getting the same Timeout Exceptions (using your latest version) which actually fails the entire session and cause 504 error from selenium. 

Also, I'm using an Augmented Driver (for other usages of DevTools) - thought it's worth mentioning. 


```
2023-10-04 11:09:31.850  WARN 24312 --- [ CDP Connection] org.openqa.selenium.devtools.Connection  : Unable to process: {"method":"Fetch.requestPaused","params":{"requestId":"interception-job-4.0","request":{"url":"https://data.pendo.io/data/ptm.gif/c661acfe-9f81-4a19-6f91-1705be2a7554?v=2.203.0_prod&ct=1696406961344&jzb=eJzVkM9PwjAUx_-Xet2vdnUbnIygEUWNiYmKMaR0T6hu7dK-SSbhf6dMDh45ag9N2u_7vLz3ed0Q7BogQ1IZUZKALKxZO7BzVLX_pdkg44m_KOM0IF_KKTR2rkoPiLJW-kx2C7AgnNGRNLVvIKQ0rcZDDYbSWAhLQAhZQXmY5WkEehn94jSg51pbeWCF2LhhHB8LxicudiCsXPkWjTWNI8NNv8thA8b5IMqT_vA8K9J86wuFBY2PYjHxQ-q2qgKCPw8yesrG088p_X6hy8vr572Sdytq6MM1K2aTUjWD-_OWjz9GPnTgnDK6j6-66oaVt3Yykw8XRXK319kh-JHS02QbHKs6ZX9UdfxPXNPt2w4q4-cs","method":"GET","headers":{"Accept":"image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8","Referer":"https://at-core-dete-2814-673.eng.cybereason.net/","User-Agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36","sec-ch-ua":"\"Not.A/Brand\";v=\"8\", \"Chromium\";v=\"114\", \"Google Chrome\";v=\"114\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"Linux\""},"initialPriority":"Low","referrerPolicy":"strict-origin-when-cross-origin"},"frameId":"XXX","resourceType":"Image"},"sessionId":"XXX"}

org.openqa.selenium.WebDriverException: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.19'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.idealized.Network.lambda$prepareToInterceptTraffic$4(Network.java:236) ~[selenium-remote-driver-4.10.0.jar:na]
	at org.openqa.selenium.devtools.Connection.lambda$handle$6(Connection.java:322) ~[selenium-remote-driver-4.10.0.jar:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:442) ~[na:na]
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1621) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[na:na]
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:287) ~[selenium-remote-driver-4.10.0.jar:na]
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:57) ~[selenium-remote-driver-4.10.0.jar:na]
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:224) ~[selenium-remote-driver-4.10.0.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.19'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:183) ~[selenium-remote-driver-4.10.0.jar:na]
	at org.openqa.selenium.devtools.DevTools.send(DevTools.java:81) ~[selenium-remote-driver-4.10.0.jar:na]
	at org.openqa.selenium.devtools.idealized.Network.lambda$prepareToInterceptTraffic$4(Network.java:233) ~[selenium-remote-driver-4.10.0.jar:na]
	... 17 common frames omitted
Caused by: java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021) ~[na:na]
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:172) ~[selenium-remote-driver-4.10.0.jar:na]
	... 19 common frames omitted
```

**Comment by cr-liorholtzman** [comment]
@MHabiib I think I found the issue, I'm using a decorator on my remoteWebDriver so it doesn't detect that its an instance of RemoteWebDriver in the start() method:

![image](https://github.com/blibli-badak/selenium-har-util/assets/79840751/208bbf9a-b7e3-4363-a047-44bb14647bcd)
![image](https://github.com/blibli-badak/selenium-har-util/assets/79840751/b5374fff-335c-4c41-8652-562b88a6ec04)

Is it something that you can fix?

**Comment by argotri** [comment]
hi @cr-liorholtzman thank you for the question
for decorated webdriver , could you please put 

`NetworkListener networkListener = new NetworkListener(driver, "har.har"); `

before your driver is converted to a decorated webdriver ?

**Comment by cr-liorholtzman** [comment]
hi @argotri , thank you for your suggestions and sorry for the late response. 

Following your suggestions, now, it seems to be failing with this error:
`java.lang.IllegalArgumentException: WebSocketUpgradeHandler but scheme isn't ws or wss: https
	at org.asynchttpclient.netty.request.NettyRequestSender.validateWebSocketRequest(NettyRequestSender.java:571) ~[async-http-client-2.12.3.jar:na]
	at org.asynchttpclient.netty.request.NettyRequestSender.sendRequest(NettyRequestSender.java:95) ~[async-http-client-2.12.3.jar:na]
	at org.asynchttpclient.netty.request.NettyRequestSender.sendNextRequest(NettyRequestSender.java:562) ~[async-http-client-2.12.3.jar:na]
	at org.asynchttpclient.netty.handler.intercept.Redirect30xInterceptor.exitAfterHandlingRedirect(Redirect30xInterceptor.java:161) ~[async-http-client-2.12.3.jar:na]
	at org.asynchttpclient.netty.handler.intercept.Interceptors.exitAfterIntercept(Interceptors.java:98) ~[async-http-client-2.12.3.jar:na]
	at org.asynchttpclient.netty.handler.WebSocketHandler.handleRead(WebSocketHandler.java:112) ~[async-http-client-2.12.3.jar:na]
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78) ~[async-http-client-2.12.3.jar:na]`

It fails when trying to create the augmented driver to start the debug

RemoteWebDriver augmenteDriver = (RemoteWebDriver)(new Augmenter()).augment(this.driver);

The error in the method is
`Unable to establish websocket connection to http://XXXX/devtools/1f397189c9c0bb917efc037baeab48e3/page`

BTW, If I try to create an augmented driver by myself (without the NetworkListener) it does work...

**Comment by cr-liorholtzman** [comment]
I'll also mention that this happens even if I just start the listener before decorating. I wonder if the issue is because the cdp is set with ws:// instead of wss:// as it normally happens in my system?

**Comment by cr-liorholtzman** [comment]
any ideas? @argotri @MHabiib
